services:
  web:
    build: ./app
    container_name: nmattt-web
    ports:
      - "5000:5000"
    environment:
      APP_MODE: fixed
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: cloud_lab
      DB_USER: app_user
      DB_PASSWORD: postgres123
      MINIO_ENDPOINT: minio:9000
      MINIO_PUBLIC_ENDPOINT: localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: public-customer-data
      SECRET_MODE: encrypted
    volumes:
      - ./secrets:/run/demo-secrets:ro
    depends_on:
      - postgres
      - minio
    networks:
      - cloud-lab

  postgres:
    image: postgres:16-alpine
    container_name: nmattt-postgres
    environment:
      POSTGRES_DB: cloud_lab
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cloud-lab

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: nmattt-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      APP_MODE: fixed
    ports:
      - "9000:9000"
      - "9002:9001"
    volumes:
      - minio-data:/data
    networks:
      - cloud-lab

  minio-init:
    image: minio/mc:RELEASE.2025-04-16T18-13-26Z
    container_name: nmattt-minio-init
    depends_on:
      - minio
    entrypoint: /bin/sh
    command: /scripts/init-buckets.sh
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      APP_MODE: fixed
    volumes:
      - ./minio/init-buckets.sh:/scripts/init-buckets.sh:ro
      - ./minio/sample-data:/sample-data:ro
    networks:
      - cloud-lab

networks:
  cloud-lab:
    driver: bridge

volumes:
  minio-data:
